environments: {
  dev: {},
  qa: {}
}

urls: {
  main_api_url: 'https://gorest.co.in/public-api'
}

token: None

general: {
  project: 'API_tests',
  git_path: 'https://github.com/Goraved/Typhon-API',
  bug: 'https://test.jira.com/browse/',
  video_folder_path: '/videos',
  link_type_test_case: 'TEST CASE',
  link_type_link: 'LINK',
  test_case: 'TEST CASE',
}
controllers: {
  users: {
    get_users: '/users',
    create_user: '/users'
  }
}
filtered_log_endpoints: [ 'GET /test']